### PR TITLE
Es6 bindings branch

### PR DESCRIPTION
**Pull request by vaibhavsinghal87**
Hi Devin,

I have added some description for es6-bindings category under a new branch 'es6-bindings-branch'. Please review.

Thanks and Regards,
Vaibhav Singhal

### CODE REVIEW

**Comment by ddoolin** [comment]
Wow, thanks! I have no problem merging. I almost feel bad because I haven't put more into this myself. Do you mind if I change the style later on to match my own (not changing the code, just any whitespace/indentation)?

**Comment by vaibhavsinghal87** [comment]
Yes please. Feel free to make any changes. I am new to Github so there are chances of error. Had a tough time setting up and running Jekyll on Windows. Now its all set up. Please make changes as per your style rules.

**Comment by ddoolin** [comment]
Sounds good. Thanks for contributing!

**Comment by vaibhavsinghal87** [comment]
I can see that bindings branch is merged but I cannot see the data in bindings post at http://es6samples.com/. Does it automatically picks up data from _site or do we need to upload it to some web host?

**Pull request merged**
